create index tournaments_created_by_idx on public.tournaments (created_by);
create index tournament_divisions_club_idx on public.tournament_divisions (club_id);
create index tournament_courts_club_idx on public.tournament_courts (club_id);
create index tournament_teams_tournament_idx on public.tournament_teams (tournament_id);
create index tournament_teams_club_idx on public.tournament_teams (club_id);
create index tournament_team_players_tournament_idx on public.tournament_team_players (tournament_id);
create index tournament_team_players_division_idx on public.tournament_team_players (division_id);
create index tournament_team_players_club_idx on public.tournament_team_players (club_id);
create index tournament_team_players_member_idx on public.tournament_team_players (club_member_id) where club_member_id is not null;
create index tournament_matches_club_idx on public.tournament_matches (club_id);
create index tournament_matches_team1_idx on public.tournament_matches (team1_id) where team1_id is not null;
create index tournament_matches_team2_idx on public.tournament_matches (team2_id) where team2_id is not null;
create index tournament_matches_winner_idx on public.tournament_matches (winner_team_id) where winner_team_id is not null;
create index tournament_matches_loser_idx on public.tournament_matches (loser_team_id) where loser_team_id is not null;
create index tournament_matches_next_idx on public.tournament_matches (next_match_id) where next_match_id is not null;
create index tournament_matches_loser_next_idx on public.tournament_matches (loser_next_match_id) where loser_next_match_id is not null;
create index tournament_games_tournament_idx on public.tournament_games (tournament_id);
create index tournament_games_club_idx on public.tournament_games (club_id);
create index tournament_audit_club_idx on public.tournament_audit_logs (club_id);
create index tournament_audit_actor_idx on public.tournament_audit_logs (actor_id) where actor_id is not null;
